macro(increment_integer _integer _increment)
    set(start_loop ${_increment})
    while (${start_loop} GREATER 0)
        math(EXPR ${_integer} "${${_integer}}+1")
        math(EXPR start_loop "${start_loop}-1")
    endwhile ()
endmacro()

macro(decrement_integer _integer _decrement)
    set(start_loop 0)
    while (${start_loop} LESS ${_decrement})
        math(EXPR ${_integer} "${${_integer}}-1")
        math(EXPR start_loop "${start_loop}+1")
    endwhile ()
endmacro()
