include(SourceSeeker)
include(ExampleSourcesSeeker)
include(ArduinoLibrarySourcesSeeker)
include(HeaderRetriever)
include(HeaderExistanceChecker)
include(SourceHeadersRetriever)
include(SourcesManager)
