if (NOT DEFINED ARDUINO_CMAKE_LINKER_FLAGS)
    set(ARDUINO_CMAKE_LINKER_FLAGS "-Wl,--gc-sections,-lm"
            CACHE STRING "Arduino-specific linker flags")
endif ()

if (${USE_ARDUINO_CMAKE_LINKER_FLAGS})
    # Setup Linker flags for "executables" (Not libraries)
    set(CMAKE_EXE_LINKER_FLAGS "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)

    # Setup Linker flags for libraries
    set(CMAKE_SHARED_LINKER_FLAGS "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)

    set(CMAKE_MODULE_LINKER_FLAGS "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
    set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "${ARDUINO_CMAKE_LINKER_FLAGS}" CACHE STRING "" FORCE)
endif ()
